### ISSUE TITLE
cannot snapshot brazil server

### ISSUE THREAD

**Issue by jbraswell** [jbraswell/dijon#44]
```
ERROR:dijon.cli.run_snapshot:error creating snapshot for 8:https://bmlt.na.org.br/ativo/main_server/
Traceback (most recent call last):
  File "/app/dijon/cli/cli.py", line 82, in run_snapshot
    snapshot.create(db, root_server)
  File "/app/dijon/snapshot/create.py", line 247, in create_snapshot
    save_meetings(db, snapshot, bmlt_meetings)
  File "/app/dijon/snapshot/create.py", line 284, in save_meetings
    db_meeting, db_meeting_formats = bmlt_meeting.to_db(db, cache)
  File "/app/dijon/snapshot/create.py", line 144, in to_db
    raise ValueError("invalid service body")
ValueError: invalid service body
```

**Comment by jbraswell** [comment]
At first glance, it looks like there are some meetings in the brazil server that point to a non-existent service body. If this is the case, the service body was probably removed, orphaning some meetings. Off hand, it seems like we should just ignore these meetings, and pretend they don't exist.
